### ISSUE TITLE
Publish package to PyPI?

### ISSUE THREAD

**Issue by PiDelport** [ashleywaite/django-more#1]
Are there any plans to publish this package to PyPI?

**Comment by ashleywaite** [comment]
I'm sorting out packaging it up now, so should be soon!

**Comment by ashleywaite** [comment]
It's on PyPI now

**Comment by PiDelport** [comment]
Awesome, thanks!

**Comment by ashleywaite** [comment]
Didn't notice a missing package in the setup.py initially because it was grabbing it from my system, and it broke the the published version. Fixed that now too
